version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    depends_on:
      - graphdb
    environment:
      - GRAPHDB_URL=http://graphdb:7200

  graphdb:
    image: ontotext/graphdb:10.1.1
    platform: linux/amd64
    ports:
      - "7200:7200"
    volumes:
      - ./kb/data:/opt/graphdb/home/data
      - ./kb/graphdb-repo-config.ttl:/opt/graphdb/home/data/repositories/tk_repo/config.ttl

  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/scraper
    depends_on:
      - graphdb
    environment:
      - GRAPHDB_URL=http://graphdb:7200
